include: "rules/common.smk"


##### Target rules #####


rule all:
    input:
        directory(expand(os.path.join(config["outdir"], "4.bismark_methylation", "{sample}"), sample=SAMPLES))


##### Modules #####

include: "rules/filter.smk"
include: "rules/align.smk"
include: "rules/dedulplicate.smk"
include: "rules/callmethy.smk"
